#!/usr/bin/env sh

PLUGIN_DIR="$CONFIG_DIR/plugins"

# --- Bar appearance ---
sketchybar --bar \
  height=32 \
  color=0xff1e2326 \
  border_width=0 \
  shadow=off \
  position=top \
  sticky=on \
  padding_left=10 \
  padding_right=10 \
  corner_radius=8 \
  y_offset=4 \
  margin=8 \
  blur_radius=20 \
  notch_width=200

# --- Default item styling ---
sketchybar --default \
  icon.font="JetBrainsMono Nerd Font:Bold:14.0" \
  icon.color=0xffd3c6aa \
  label.font="GeistMono Nerd Font:Regular:13.0" \
  label.color=0xffd3c6aa \
  background.color=0xff272e33 \
  background.corner_radius=6 \
  background.height=24 \
  padding_left=4 \
  padding_right=4 \
  label.padding_left=4 \
  label.padding_right=4 \
  icon.padding_left=8 \
  icon.padding_right=4

# --- Left: Spaces ---
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8")

for i in "${!SPACE_ICONS[@]}"; do
  sid=$((i + 1))
  sketchybar --add space space.$sid left \
    --set space.$sid \
      space=$sid \
      icon="${SPACE_ICONS[i]}" \
      icon.font="GeistMono Nerd Font:Bold:13.0" \
      icon.color=0xffd3c6aa \
      icon.highlight_color=0xff1e2326 \
      background.color=0xff272e33 \
      background.drawing=off \
      label.drawing=off \
      script="$PLUGIN_DIR/space.sh" \
      click_script="yabai -m space --focus $sid"
done

# --- Left: Front app ---
sketchybar --add item front_app left \
  --set front_app \
    icon.drawing=off \
    label.font="GeistMono Nerd Font:Bold:13.0" \
    label.color=0xffa7c080 \
    background.drawing=on \
    background.color=0xff272e33 \
    background.padding_left=8 \
    background.padding_right=8 \
    script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched

# --- Center: Clock ---
sketchybar --add item clock center \
  --set clock \
    update_freq=30 \
    icon="" \
    icon.color=0xff88c0d0 \
    label.color=0xffd3c6aa \
    background.drawing=on \
    script="$PLUGIN_DIR/clock.sh"

# --- Right: Wifi ---
sketchybar --add item wifi right \
  --set wifi \
    update_freq=30 \
    icon.color=0xff83c092 \
    background.drawing=on \
    script="$PLUGIN_DIR/wifi.sh" \
  --subscribe wifi wifi_change

# --- Right: Volume ---
sketchybar --add item volume right \
  --set volume \
    icon.color=0xffdbbc7f \
    background.drawing=on \
    script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change

# --- Right: Battery ---
sketchybar --add item battery right \
  --set battery \
    update_freq=120 \
    icon.color=0xffa7c080 \
    background.drawing=on \
    script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change

sketchybar --update
echo "sketchybar configuration loaded"
